### ISSUE TITLE
Integrity error in `group_search_async`

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#213]
```
Traceback (most recent call last):
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 3322, in execute_sql
    cursor.execute(sql, params or ())
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/mysql/connector/cursor.py", line 572, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/mysql/connector/connection.py", line 922, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/mysql/connector/connection.py", line 732, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '363017-1117' for key 'file_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chimedat/git/alpenhorn2/alpenhorn/scheduler/pool.py", line 97, in run
    finished = task()
  File "/home/chimedat/git/alpenhorn2/alpenhorn/scheduler/task.py", line 113, in __call__
    result = self._func(self, *self._args, **self._kwargs)
  File "/home/chimedat/git/alpenhorn2/alpenhorn/io/_default_asyncs.py", line 353, in group_search_async
    ArchiveFileCopy.create(
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 6741, in create
    inst.save(force_insert=True)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 6951, in save
    pk = self.insert(**field_dict).execute()
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 2036, in inner
    return method(self, database, *args, **kwargs)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 2107, in execute
    return self._execute(database)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 2912, in _execute
    return super(Insert, self)._execute(database)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 2625, in _execute
    cursor = database.execute(self)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 3330, in execute
    return self.execute_sql(sql, params)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/chimedb/core/connectdb.py", line 271, in execute_sql
    cursor = super().execute_sql(sql, params, commit)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 3320, in execute_sql
    with __exception_wrapper__:
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 3088, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 196, in reraise
    raise value.with_traceback(tb)
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/peewee.py", line 3322, in execute_sql
    cursor.execute(sql, params or ())
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/mysql/connector/cursor.py", line 572, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/mysql/connector/connection.py", line 922, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/chimedat/alpenvenv/lib/python3.10/site-packages/mysql/connector/connection.py", line 732, in _handle_result
    raise errors.get_exception(packet)
peewee.IntegrityError: (1062, "1062 (23000): Duplicate entry '363017-1117' for key 'file_id'", '23000')
```

**Comment by ketiltrout** [comment]
https://github.com/radiocosmology/alpenhorn/blob/1d17a4686ccf5cee20846ea2f27fc46f7e1c8c5d/alpenhorn/io/_default_asyncs.py#L351C1-L351C23
Yeah, `count` can be zero if the record exists, but already has ` has_file="M"`.  Should do an actual `.get` to search for it.
