### ISSUE TITLE
Better handling of illegal value of `--storage_type` in `create_node`

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#46]
Legal values are "A", "T" and "F", and we could check those as part of Click's argument processing. We don't, and so they fail at the DB level, with a very cryptic error message:

```
$ alpenhorn create_node --storage_type=transport t1 /mnt/t1 host_1 transport
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3220, in get
    return next(clone.execute())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2363, in next
    obj = self.iterate()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2345, in iterate
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/alpenhorn/client.py", line 1015, in create_node
    this_node = st.StorageNode.get(name=node_name)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4988, in get
    return sq.get()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3224, in get
    % self.sql())
alpenhorn.storage.StorageNodeDoesNotExist: Instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`name`, `t1`.`root`, `t1`.`host`, `t1`.`username`, `t1`.`address`, `t1`.`group_id`, `t1`.`mounted`, `t1`.`auto_import`, `t1`.`suspect`, `t1`.`storage_type`, `t1`.`max_total_gb`, `t1`.`min_avail_gb`, `t1`.`avail_gb`, `t1`.`avail_gb_last_checked`, `t1`.`min_delete_age_days`, `t1`.`notes` FROM `storagenode` AS t1 WHERE (`t1`.`name` = %s)
PARAMS: ['t1']

During handling of the above exception, another exception occurred:
[... repeats several times ...]
```

**Comment by jrs65** [comment]
Again, we should fix this one.
