### ISSUE TITLE
Better handling of bad target group in `sync`

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#47]
Specifying a non-existent group name as the value of the `--target` argument to `alpenhorn sync` prints the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3220, in get
    return next(clone.execute())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2363, in next
    obj = self.iterate()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2345, in iterate
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/alpenhorn/client.py", line 121, in sync
    target_group = st.StorageGroup.get(name=target)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4988, in get
    return sq.get()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3224, in get
    % self.sql())
alpenhorn.storage.StorageGroupDoesNotExist: Instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`name`, `t1`.`notes` FROM `storagegroup` AS t1 WHERE (`t1`.`name` = %s)
PARAMS: ['node_3']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/alpenhorn", line 11, in <module>
    load_entry_point('alpenhorn==2.0.0a1', 'console_scripts', 'alpenhorn')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/alpenhorn/client.py", line 123, in sync
    raise RuntimeError("Target group \"%s\" does not exist in the DB." % target)
RuntimeError: Target group "node_3" does not exist in the DB.
```

**Comment by jrs65** [comment]
Yeah. I guess we work on this one. It actually does send a reasonable error message, but it's hard to see at the end of the traceback. Probably we should avoid throwing exceptions in the client.

One option might be to try and catch exceptions and only report the last message on the command line unless a `--verbose` argument (or maybe `--debug\--traceback`) argument has been set, at which point you let the whole traceback bubble up.
